# Generated by Django 3.2.8 on 2021-10-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_auto_20211021_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
